version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ai-payment-intelligence-app
    command: bash /src/entrypoint.sh
    volumes:
      - ${MODEL_PATH_SRC}:/src/
      - ./docker/entrypoint.sh:/src/entrypoint.sh
    ports:
      - "8010:8010"
    env_file:
      - .env